apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
        - name: product-container

          image: samruddhi2211/product-service:v1

          ports:
            - containerPort: 3002

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "128Mi"